# Generated by Django 5.2.7 on 2025-11-25 17:46

from django.db import migrations, models


def populate_tag_id(apps, schema_editor):
    """Mevcut Tag kayıtları için tag_id'yi name'den türet"""
    Tag = apps.get_model('api', 'Tag')
    for tag in Tag.objects.all():
        if not tag.tag_id:
            # name'i tag_id olarak kullan, özel karakterleri temizle
            tag.tag_id = tag.name.lower().replace(' ', '_').replace('-', '_')
            tag.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_request_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='label',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.RunPython(populate_tag_id, migrations.RunPython.noop),
    ]
