# Generated by Django 5.2.7 on 2025-11-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_tag_description_tag_label_tag_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
