# Generated by Django 5.2.7 on 2025-11-25 17:49

from django.db import migrations, models


def convert_tag_id_to_integer(apps, schema_editor):
    """Mevcut tag kayıtları için sıralı integer tag_id değerleri atayalım"""
    Tag = apps.get_model('api', 'Tag')
    # Tüm tag'leri id'ye göre sıralayıp sırayla integer değer atayalım
    tags = Tag.objects.all().order_by('id')
    for index, tag in enumerate(tags, start=1):
        # Raw SQL kullanarak direkt güncelleme yapalım
        from django.db import connection
        with connection.cursor() as cursor:
            cursor.execute(
                "UPDATE api_tag SET tag_id = %s WHERE id = %s",
                [index, tag.id]
            )


def reverse_convert_tag_id(apps, schema_editor):
    """Reverse migration - tag_id'yi string'e çevir (gerekirse)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_tag_tag_id'),
    ]

    operations = [
        # Önce eski CharField'ı kaldır
        migrations.RemoveField(
            model_name='tag',
            name='tag_id',
        ),
        # Yeni IntegerField ekle (nullable)
        migrations.AddField(
            model_name='tag',
            name='tag_id',
            field=models.IntegerField(unique=True, null=True, blank=True),
        ),
        # Data migration ile integer değerler atayalım
        migrations.RunPython(convert_tag_id_to_integer, reverse_convert_tag_id),
        # Sonra nullable'ı kaldır
        migrations.AlterField(
            model_name='tag',
            name='tag_id',
            field=models.IntegerField(unique=True),
        ),
    ]
