# Generated by Django 5.2.7 on 2025-11-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_tag_tag_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interested_tags',
            field=models.ManyToManyField(blank=True, related_name='interested_profiles', to='api.tag'),
        ),
    ]
