# Generated by Django 5.2.7 on 2025-11-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_profile_interested_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
