# Generated by Django 5.2.7 on 2025-12-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_post_latitude_post_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location_display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
