# Generated by Django 5.2.7 on 2025-12-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_post_location_display_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.TextField(
                blank=True,
                default="https://placehold.co/100x100/EBF8FF/3B82F6?text=User",
                null=True,
            ),
        ),
    ]
