# Generated by Django 5.2.7 on 2025-12-02 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_profile_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="time_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(10.0),
                ],
            ),
        ),
    ]
