# Generated by Django 5.2.7 on 2025-12-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_remove_profile_skills_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="like_count",
            field=models.IntegerField(default=0),
        ),
    ]
