# Generated by Django 5.2.7 on 2025-12-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_comment_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
