# Generated by Django 5.2.7 on 2025-12-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_proposal_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='date',
        ),
        migrations.AddField(
            model_name='proposal',
            name='proposed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='proposed_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
