# Generated by Django 5.2.7 on 2025-12-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_proposal_date_proposal_proposed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='proposed_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
