# Generated by Django 5.2.7 on 2025-12-06 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_proposal_proposed_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='request',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
