# Generated by Django 5.2.7 on 2025-12-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_chat_request_delete_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='provider_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposal',
            name='requester_approved',
            field=models.BooleanField(default=False),
        ),
    ]
