# Generated by Django 5.2.7 on 2025-12-06 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='communication',
            field=models.IntegerField(default=3, help_text='Rating from 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='review',
            name='work_quality',
            field=models.IntegerField(default=3, help_text='Rating from 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
