# Generated by Django 5.2.7 on 2025-12-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_job_cancelled_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('not_showed_up', 'Not Showed Up'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
