# Generated by Django 5.2.7 on 2025-12-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0035_forumtopic_forumcomment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="forumtopic",
            name="semantic_tag",
        ),
        migrations.AddField(
            model_name="forumtopic",
            name="semantic_tags",
            field=models.ManyToManyField(
                blank=True, related_name="forum_topics", to="api.tag"
            ),
        ),
    ]
