# Generated by Django 5.2.7 on 2025-12-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0036_remove_forumtopic_semantic_tag_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="forumtopic",
            name="image",
            field=models.TextField(
                blank=True, help_text="Base64 encoded image or image URL", null=True
            ),
        ),
    ]
