# Generated by Django 5.2.7 on 2025-12-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0039_comment_is_hidden_comment_report_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Optional comment about the reviewed user",
                null=True,
            ),
        ),
    ]
