# Generated by Django 5.2.7 on 2025-12-11 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0040_review_comment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="chat",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="chat",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chats",
                to="api.post",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chat",
            unique_together={("participant1", "participant2", "post")},
        ),
    ]
