# Generated by Django 5.2.7 on 2025-12-12 12:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_proposal_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['requester', 'status'], name='api_proposa_request_78f54e_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['provider', 'status'], name='api_proposa_provide_f3326a_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['status', 'created_at'], name='api_proposa_status_98ae66_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['requester', 'provider'], name='api_proposa_request_5d3f94_idx'),
        ),
    ]
