# Generated by Django 5.2.7 on 2025-12-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0043_proposal_api_proposa_request_78f54e_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
