# Generated by Django 5.2.7 on 2025-12-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_post_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, help_text="User's birth date for age verification", null=True),
        ),
    ]
